# Generated by Django 4.2.4 on 2023-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0006_productvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_visit_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد بازدید محصول'),
        ),
    ]
