# Generated by Django 4.2.4 on 2023-09-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Module', '0008_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقالات'},
        ),
    ]
